language: python
python:
    - 2.7
    - 3.6
addons:
  postgresql: "9.6"
install:
    - pip install -U setuptools coveralls
    - python bootstrap.py
    - bin/buildout
before_script:
    - psql -c "create user pjpersist with createdb password 'pjpersist';" -U postgres
script:
    - bin/test -v1
notifications:
    email: false
after_success:
  - coveralls
