language: python
python:
    - 2.7
services: mongodb
install:
    - virtualenv env
    - env/bin/pip install -U setuptools distribute
    - env/bin/python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
